/*
 * generated by Xtext 2.30.0
 */
package org.sdu.dsl4ifc.generator

import org.sdu.dsl4ifc.generator.depedencyGraph.core.Block

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
class FilterBlockCatalog { 
	
	Block<?> select;
	
	// One statement support
	
	new() {
		
		
		
	}
	
	def Block<?> selectBlock() {
		
	}
}