/*
 * generated by Xtext 2.30.0
 */
package org.sdu.dsl4ifc.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SustainLangUiModule extends AbstractSustainLangUiModule {

	public SustainLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
