/*
 * generated by Xtext 2.30.0
 */
package org.sdu.dsl4ifc.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.sdu.dsl4ifc.SustainLangRuntimeModule;
import org.sdu.dsl4ifc.SustainLangStandaloneSetup;
import org.sdu.dsl4ifc.ide.SustainLangIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class SustainLangWebSetup extends SustainLangStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SustainLangRuntimeModule(), new SustainLangIdeModule(), new SustainLangWebModule()));
	}
	
}
