/*
 * generated by Xtext 2.30.0
 */
package org.sdu.dsl4ifc.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class SustainLangWebModule extends AbstractSustainLangWebModule {
}
