/*
 * generated by Xtext 2.30.0
 */
package org.sdu.dsl4ifc;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SustainLangRuntimeModule extends AbstractSustainLangRuntimeModule {
}
