/*
 * generated by Xtext 2.30.0
 */
package org.sdu.dsl4ifc;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SustainLangStandaloneSetup extends SustainLangStandaloneSetupGenerated {

	public static void doSetup() {
		new SustainLangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
