/*
 * generated by Xtext 2.30.0
 */
package org.sdu.dsl4ifc.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.sdu.dsl4ifc.SustainLangRuntimeModule;
import org.sdu.dsl4ifc.SustainLangStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SustainLangIdeSetup extends SustainLangStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SustainLangRuntimeModule(), new SustainLangIdeModule()));
	}
	
}
