/*
 * generated by Xtext 2.30.0
 */
package org.sdu.dsl4ifc.tests

import java.io.File
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.junit.jupiter.api.BeforeAll
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

import static org.junit.Assert.*

@ExtendWith(InjectionExtension)
@InjectWith(SustainLangInjectorProvider)
class BlockTest {

	static File file;

	@BeforeAll
	def static void setUpBeforeClass() throws Exception {
		file = new File("/Users/andreasedalpedersen/SDU-local/Speciale/dsl4ifc/DSL4IFC/org.sdu.dsl4ifc.parent/org.sdu.dsl4ifc.tests/src/org/sdu/dsl4ifc/tests/Duplex_A_20110907.ifc")
		
	}
	
	@Test
	def void fileExists() {
		//assertTrue("File does not exist", file.exists)
		//assertTrue("File is an actual file", file.isFile)
	}
	
	@Test
	def void parseTest() {
		
	}
}
