/*
 * generated by Xtext 2.30.0
 */
package org.sdu.dsl4ifc.tests

import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(SustainLangInjectorProvider)
class IfcExtractionTest {

}
